on:
  push:
    branches: 
      - main

  workflow-dispatch:

jobs:
  hello-world-job:
  name: A job to say hello
  runs-on: ubuntu-latest
  steps:
    - name: Hello world action step
      id: hello
      uses: actions/hello-world-docker-action@v1
      with:
        who-to-greet: 'Uche Madu'
      
    - name: Get the output time
      run: "The time was ${{ steps.hello.outputs.time }}"